stages:
  - deploy

deploy:
  stage: deploy
  image: python:3.9.1-slim
  script:
    - docker build -t covid_bot:$TAG .
    - docker run -d --env TOKEN=$TOKEN --name covid_bot -it covid_bot:$TAG
  tags:
    - covid-docker
  timeout: 90m

variables:
  TAG: $CI_COMMIT_BRANCH-$CI_JOB_ID
