stages:
  - clear
  - deploy

clear:
  stage: clear
  allow_failure: true
  script:
    - docker stop covid_bot
  tags:
    - covid

deploy:
  stage: deploy
  variables:
    TAG: $CI_COMMIT_BRANCH-$CI_JOB_ID
  script:
    - docker build -t covid_bot:$TAG .
    - docker run -d --name covid_bot -it covid_bot:TAG
  tags:
    - covid