DATABASE_USERS = "CREATE TABLE IF NOT EXISTS USERS (id INTEGER PRIMARY KEY , subscribe BOOLEAN, root BOOLEAN);"
DATABASE_STATIC = "CREATE TABLE IF NOT EXISTS STATISTIC " \
                  "(id INTEGER PRIMARY KEY AUTOINCREMENT, timepredict INTEGER, data TEXT, general BOOLEAN);"

