DATABASE_USERS = "CREATE TABLE IF NOT EXISTS USERS (id INTEGER PRIMARY KEY , subscribe BOOLEAN, root BOOLEAN);"
DATABASE_STATIC = "CREATE TABLE IF NOT EXISTS STATIC (id INTEGER PRIMARY KEY AUTOINCREMENT, timestamp INTEGER, data TEXT);"

